// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_pb.proto

package serverpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RangeRequest_SortOrder int32

const (
	RangeRequest_NONE    RangeRequest_SortOrder = 0
	RangeRequest_ASCEND  RangeRequest_SortOrder = 1
	RangeRequest_DESCEND RangeRequest_SortOrder = 2
)

var RangeRequest_SortOrder_name = map[int32]string{
	0: "NONE",
	1: "ASCEND",
	2: "DESCEND",
}

var RangeRequest_SortOrder_value = map[string]int32{
	"NONE":    0,
	"ASCEND":  1,
	"DESCEND": 2,
}

func (x RangeRequest_SortOrder) String() string {
	return proto.EnumName(RangeRequest_SortOrder_name, int32(x))
}

func (RangeRequest_SortOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{3, 0}
}

type RangeRequest_SortTarget int32

const (
	RangeRequest_KEY   RangeRequest_SortTarget = 0
	RangeRequest_VALUE RangeRequest_SortTarget = 1
)

var RangeRequest_SortTarget_name = map[int32]string{
	0: "KEY",
	1: "VALUE",
}

var RangeRequest_SortTarget_value = map[string]int32{
	"KEY":   0,
	"VALUE": 1,
}

func (x RangeRequest_SortTarget) String() string {
	return proto.EnumName(RangeRequest_SortTarget_name, int32(x))
}

func (RangeRequest_SortTarget) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{3, 1}
}

type Compare_CompareResult int32

const (
	Compare_EQUAL     Compare_CompareResult = 0
	Compare_GREATER   Compare_CompareResult = 1
	Compare_LESS      Compare_CompareResult = 2
	Compare_NOT_EQUAL Compare_CompareResult = 3
	Compare_EXIST     Compare_CompareResult = 4
	Compare_NOT_EXIST Compare_CompareResult = 5
)

var Compare_CompareResult_name = map[int32]string{
	0: "EQUAL",
	1: "GREATER",
	2: "LESS",
	3: "NOT_EQUAL",
	4: "EXIST",
	5: "NOT_EXIST",
}

var Compare_CompareResult_value = map[string]int32{
	"EQUAL":     0,
	"GREATER":   1,
	"LESS":      2,
	"NOT_EQUAL": 3,
	"EXIST":     4,
	"NOT_EXIST": 5,
}

func (x Compare_CompareResult) String() string {
	return proto.EnumName(Compare_CompareResult_name, int32(x))
}

func (Compare_CompareResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{11, 0}
}

type Compare_CompareTarget int32

const (
	Compare_VALUE Compare_CompareTarget = 0
	Compare_KEY   Compare_CompareTarget = 1
)

var Compare_CompareTarget_name = map[int32]string{
	0: "VALUE",
	1: "KEY",
}

var Compare_CompareTarget_value = map[string]int32{
	"VALUE": 0,
	"KEY":   1,
}

func (x Compare_CompareTarget) String() string {
	return proto.EnumName(Compare_CompareTarget_name, int32(x))
}

func (Compare_CompareTarget) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{11, 1}
}

type KeyValue struct {
	// key is the key in bytes. An empty key is not allowed.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// value is the value held by the key, in bytes.
	Value                []byte   `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{0}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Metadata struct {
	NodeID               uint64   `protobuf:"varint,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	ClusterID            uint64   `protobuf:"varint,2,opt,name=ClusterID,proto3" json:"ClusterID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{1}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetNodeID() uint64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *Metadata) GetClusterID() uint64 {
	if m != nil {
		return m.ClusterID
	}
	return 0
}

type ResponseHeader struct {
	// cluster_id is the ID of the cluster which sent the response.
	ClusterId uint64 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// member_id is the ID of the member which sent the response.
	MemberId uint64 `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	// raft_term is the raft term when the request was applied.
	RaftTerm             uint64   `protobuf:"varint,3,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{2}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetClusterId() uint64 {
	if m != nil {
		return m.ClusterId
	}
	return 0
}

func (m *ResponseHeader) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *ResponseHeader) GetRaftTerm() uint64 {
	if m != nil {
		return m.RaftTerm
	}
	return 0
}

type RangeRequest struct {
	// key is the first key for the range. If range_end is not given, the request only looks up key.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// range_end is the upper bound on the requested range [key, range_end).
	// If range_end is '\0', the range is all keys >= key.
	// If range_end is key plus one (e.g., "aa"+1 == "ab", "a\xff"+1 == "b"),
	// then the range request gets all keys prefixed with key.
	// If both key and range_end are '\0', then the range request returns all keys.
	RangeEnd []byte `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	// limit is a limit on the number of keys returned for the request. When limit is set to 0,
	// it is treated as no limit.
	Limit int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// sort_order is the order for returned sorted results.
	SortOrder RangeRequest_SortOrder `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=serverpb.RangeRequest_SortOrder" json:"sort_order,omitempty"`
	// sort_target is the key-value field to use for sorting.
	SortTarget RangeRequest_SortTarget `protobuf:"varint,5,opt,name=sort_target,json=sortTarget,proto3,enum=serverpb.RangeRequest_SortTarget" json:"sort_target,omitempty"`
	// serializable sets the range request to use serializable member-local reads.
	// Range requests are linearizable by default; linearizable requests have higher
	// latency and lower throughput than serializable requests but reflect the current
	// consensus of the cluster. For better performance, in exchange for possible stale reads,
	// a serializable range request is served locally without needing to reach consensus
	// with other nodes in the cluster.
	Serializable bool `protobuf:"varint,6,opt,name=serializable,proto3" json:"serializable,omitempty"`
	// keys_only when set returns only the keys and not the values.
	KeysOnly bool `protobuf:"varint,7,opt,name=keys_only,json=keysOnly,proto3" json:"keys_only,omitempty"`
	// count_only when set returns only the count of the keys in the range.
	CountOnly            bool     `protobuf:"varint,8,opt,name=count_only,json=countOnly,proto3" json:"count_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeRequest) Reset()         { *m = RangeRequest{} }
func (m *RangeRequest) String() string { return proto.CompactTextString(m) }
func (*RangeRequest) ProtoMessage()    {}
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{3}
}

func (m *RangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeRequest.Unmarshal(m, b)
}
func (m *RangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeRequest.Marshal(b, m, deterministic)
}
func (m *RangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeRequest.Merge(m, src)
}
func (m *RangeRequest) XXX_Size() int {
	return xxx_messageInfo_RangeRequest.Size(m)
}
func (m *RangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RangeRequest proto.InternalMessageInfo

func (m *RangeRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RangeRequest) GetRangeEnd() []byte {
	if m != nil {
		return m.RangeEnd
	}
	return nil
}

func (m *RangeRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RangeRequest) GetSortOrder() RangeRequest_SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return RangeRequest_NONE
}

func (m *RangeRequest) GetSortTarget() RangeRequest_SortTarget {
	if m != nil {
		return m.SortTarget
	}
	return RangeRequest_KEY
}

func (m *RangeRequest) GetSerializable() bool {
	if m != nil {
		return m.Serializable
	}
	return false
}

func (m *RangeRequest) GetKeysOnly() bool {
	if m != nil {
		return m.KeysOnly
	}
	return false
}

func (m *RangeRequest) GetCountOnly() bool {
	if m != nil {
		return m.CountOnly
	}
	return false
}

type RangeResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// kvs is the list of key-value pairs matched by the range request.
	// kvs is empty when count is requested.
	Kvs []*KeyValue `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	// more indicates if there are more keys to return in the requested range.
	More bool `protobuf:"varint,3,opt,name=more,proto3" json:"more,omitempty"`
	// count is set to the number of keys within the range when requested.
	Count                int64    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeResponse) Reset()         { *m = RangeResponse{} }
func (m *RangeResponse) String() string { return proto.CompactTextString(m) }
func (*RangeResponse) ProtoMessage()    {}
func (*RangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{4}
}

func (m *RangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeResponse.Unmarshal(m, b)
}
func (m *RangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeResponse.Marshal(b, m, deterministic)
}
func (m *RangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeResponse.Merge(m, src)
}
func (m *RangeResponse) XXX_Size() int {
	return xxx_messageInfo_RangeResponse.Size(m)
}
func (m *RangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RangeResponse proto.InternalMessageInfo

func (m *RangeResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RangeResponse) GetKvs() []*KeyValue {
	if m != nil {
		return m.Kvs
	}
	return nil
}

func (m *RangeResponse) GetMore() bool {
	if m != nil {
		return m.More
	}
	return false
}

func (m *RangeResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type PutRequest struct {
	// key is the key, in bytes, to put into the key-value store.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// value is the value, in bytes, to associate with the key in the key-value store.
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{5}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{6}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type DeleteRangeRequest struct {
	// key is the first key to delete in the range.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// range_end is the key following the last key to delete for the range [key, range_end).
	// If range_end is not given, the range is defined to contain only the key argument.
	// If range_end is one bit larger than the given key, then the range is all the keys
	// with the prefix (the given key).
	// If range_end is '\0', the range is all keys greater than or equal to the key argument.
	RangeEnd             []byte   `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRangeRequest) Reset()         { *m = DeleteRangeRequest{} }
func (m *DeleteRangeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRangeRequest) ProtoMessage()    {}
func (*DeleteRangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{7}
}

func (m *DeleteRangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRangeRequest.Unmarshal(m, b)
}
func (m *DeleteRangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRangeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRangeRequest.Merge(m, src)
}
func (m *DeleteRangeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRangeRequest.Size(m)
}
func (m *DeleteRangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRangeRequest proto.InternalMessageInfo

func (m *DeleteRangeRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DeleteRangeRequest) GetRangeEnd() []byte {
	if m != nil {
		return m.RangeEnd
	}
	return nil
}

type DeleteRangeResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// deleted is the number of keys deleted by the delete range request.
	Deleted              int64    `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRangeResponse) Reset()         { *m = DeleteRangeResponse{} }
func (m *DeleteRangeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRangeResponse) ProtoMessage()    {}
func (*DeleteRangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{8}
}

func (m *DeleteRangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRangeResponse.Unmarshal(m, b)
}
func (m *DeleteRangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRangeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRangeResponse.Merge(m, src)
}
func (m *DeleteRangeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRangeResponse.Size(m)
}
func (m *DeleteRangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRangeResponse proto.InternalMessageInfo

func (m *DeleteRangeResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DeleteRangeResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type RequestOp struct {
	// request is a union of request types accepted by a transaction.
	//
	// Types that are valid to be assigned to Request:
	//	*RequestOp_RequestRange
	//	*RequestOp_RequestPut
	//	*RequestOp_RequestDeleteRange
	//	*RequestOp_RequestTxn
	Request              isRequestOp_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RequestOp) Reset()         { *m = RequestOp{} }
func (m *RequestOp) String() string { return proto.CompactTextString(m) }
func (*RequestOp) ProtoMessage()    {}
func (*RequestOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{9}
}

func (m *RequestOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestOp.Unmarshal(m, b)
}
func (m *RequestOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestOp.Marshal(b, m, deterministic)
}
func (m *RequestOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestOp.Merge(m, src)
}
func (m *RequestOp) XXX_Size() int {
	return xxx_messageInfo_RequestOp.Size(m)
}
func (m *RequestOp) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestOp.DiscardUnknown(m)
}

var xxx_messageInfo_RequestOp proto.InternalMessageInfo

type isRequestOp_Request interface {
	isRequestOp_Request()
}

type RequestOp_RequestRange struct {
	RequestRange *RangeRequest `protobuf:"bytes,1,opt,name=request_range,json=requestRange,proto3,oneof"`
}

type RequestOp_RequestPut struct {
	RequestPut *PutRequest `protobuf:"bytes,2,opt,name=request_put,json=requestPut,proto3,oneof"`
}

type RequestOp_RequestDeleteRange struct {
	RequestDeleteRange *DeleteRangeRequest `protobuf:"bytes,3,opt,name=request_delete_range,json=requestDeleteRange,proto3,oneof"`
}

type RequestOp_RequestTxn struct {
	RequestTxn *TxnRequest `protobuf:"bytes,4,opt,name=request_txn,json=requestTxn,proto3,oneof"`
}

func (*RequestOp_RequestRange) isRequestOp_Request() {}

func (*RequestOp_RequestPut) isRequestOp_Request() {}

func (*RequestOp_RequestDeleteRange) isRequestOp_Request() {}

func (*RequestOp_RequestTxn) isRequestOp_Request() {}

func (m *RequestOp) GetRequest() isRequestOp_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *RequestOp) GetRequestRange() *RangeRequest {
	if x, ok := m.GetRequest().(*RequestOp_RequestRange); ok {
		return x.RequestRange
	}
	return nil
}

func (m *RequestOp) GetRequestPut() *PutRequest {
	if x, ok := m.GetRequest().(*RequestOp_RequestPut); ok {
		return x.RequestPut
	}
	return nil
}

func (m *RequestOp) GetRequestDeleteRange() *DeleteRangeRequest {
	if x, ok := m.GetRequest().(*RequestOp_RequestDeleteRange); ok {
		return x.RequestDeleteRange
	}
	return nil
}

func (m *RequestOp) GetRequestTxn() *TxnRequest {
	if x, ok := m.GetRequest().(*RequestOp_RequestTxn); ok {
		return x.RequestTxn
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RequestOp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RequestOp_RequestRange)(nil),
		(*RequestOp_RequestPut)(nil),
		(*RequestOp_RequestDeleteRange)(nil),
		(*RequestOp_RequestTxn)(nil),
	}
}

type ResponseOp struct {
	// response is a union of response types returned by a transaction.
	//
	// Types that are valid to be assigned to Response:
	//	*ResponseOp_ResponseRange
	//	*ResponseOp_ResponsePut
	//	*ResponseOp_ResponseDeleteRange
	//	*ResponseOp_ResponseTxn
	Response             isResponseOp_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ResponseOp) Reset()         { *m = ResponseOp{} }
func (m *ResponseOp) String() string { return proto.CompactTextString(m) }
func (*ResponseOp) ProtoMessage()    {}
func (*ResponseOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{10}
}

func (m *ResponseOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseOp.Unmarshal(m, b)
}
func (m *ResponseOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseOp.Marshal(b, m, deterministic)
}
func (m *ResponseOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseOp.Merge(m, src)
}
func (m *ResponseOp) XXX_Size() int {
	return xxx_messageInfo_ResponseOp.Size(m)
}
func (m *ResponseOp) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseOp.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseOp proto.InternalMessageInfo

type isResponseOp_Response interface {
	isResponseOp_Response()
}

type ResponseOp_ResponseRange struct {
	ResponseRange *RangeResponse `protobuf:"bytes,1,opt,name=response_range,json=responseRange,proto3,oneof"`
}

type ResponseOp_ResponsePut struct {
	ResponsePut *PutResponse `protobuf:"bytes,2,opt,name=response_put,json=responsePut,proto3,oneof"`
}

type ResponseOp_ResponseDeleteRange struct {
	ResponseDeleteRange *DeleteRangeResponse `protobuf:"bytes,3,opt,name=response_delete_range,json=responseDeleteRange,proto3,oneof"`
}

type ResponseOp_ResponseTxn struct {
	ResponseTxn *TxnResponse `protobuf:"bytes,4,opt,name=response_txn,json=responseTxn,proto3,oneof"`
}

func (*ResponseOp_ResponseRange) isResponseOp_Response() {}

func (*ResponseOp_ResponsePut) isResponseOp_Response() {}

func (*ResponseOp_ResponseDeleteRange) isResponseOp_Response() {}

func (*ResponseOp_ResponseTxn) isResponseOp_Response() {}

func (m *ResponseOp) GetResponse() isResponseOp_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ResponseOp) GetResponseRange() *RangeResponse {
	if x, ok := m.GetResponse().(*ResponseOp_ResponseRange); ok {
		return x.ResponseRange
	}
	return nil
}

func (m *ResponseOp) GetResponsePut() *PutResponse {
	if x, ok := m.GetResponse().(*ResponseOp_ResponsePut); ok {
		return x.ResponsePut
	}
	return nil
}

func (m *ResponseOp) GetResponseDeleteRange() *DeleteRangeResponse {
	if x, ok := m.GetResponse().(*ResponseOp_ResponseDeleteRange); ok {
		return x.ResponseDeleteRange
	}
	return nil
}

func (m *ResponseOp) GetResponseTxn() *TxnResponse {
	if x, ok := m.GetResponse().(*ResponseOp_ResponseTxn); ok {
		return x.ResponseTxn
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ResponseOp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ResponseOp_ResponseRange)(nil),
		(*ResponseOp_ResponsePut)(nil),
		(*ResponseOp_ResponseDeleteRange)(nil),
		(*ResponseOp_ResponseTxn)(nil),
	}
}

type Compare struct {
	// result is logical comparison operation for this comparison.
	Result Compare_CompareResult `protobuf:"varint,1,opt,name=result,proto3,enum=serverpb.Compare_CompareResult" json:"result,omitempty"`
	// target is the key-value field to inspect for the comparison.
	Target Compare_CompareTarget `protobuf:"varint,2,opt,name=target,proto3,enum=serverpb.Compare_CompareTarget" json:"target,omitempty"`
	// key is the subject key for the comparison operation.
	Key []byte `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to TargetUnion:
	//	*Compare_Value
	TargetUnion isCompare_TargetUnion `protobuf_oneof:"target_union"`
	// range_end compares the given target to all keys in the range [key, range_end).
	// See RangeRequest for more details on key ranges.
	RangeEnd             []byte   `protobuf:"bytes,100,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Compare) Reset()         { *m = Compare{} }
func (m *Compare) String() string { return proto.CompactTextString(m) }
func (*Compare) ProtoMessage()    {}
func (*Compare) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{11}
}

func (m *Compare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Compare.Unmarshal(m, b)
}
func (m *Compare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Compare.Marshal(b, m, deterministic)
}
func (m *Compare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Compare.Merge(m, src)
}
func (m *Compare) XXX_Size() int {
	return xxx_messageInfo_Compare.Size(m)
}
func (m *Compare) XXX_DiscardUnknown() {
	xxx_messageInfo_Compare.DiscardUnknown(m)
}

var xxx_messageInfo_Compare proto.InternalMessageInfo

func (m *Compare) GetResult() Compare_CompareResult {
	if m != nil {
		return m.Result
	}
	return Compare_EQUAL
}

func (m *Compare) GetTarget() Compare_CompareTarget {
	if m != nil {
		return m.Target
	}
	return Compare_VALUE
}

func (m *Compare) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type isCompare_TargetUnion interface {
	isCompare_TargetUnion()
}

type Compare_Value struct {
	Value []byte `protobuf:"bytes,4,opt,name=value,proto3,oneof"`
}

func (*Compare_Value) isCompare_TargetUnion() {}

func (m *Compare) GetTargetUnion() isCompare_TargetUnion {
	if m != nil {
		return m.TargetUnion
	}
	return nil
}

func (m *Compare) GetValue() []byte {
	if x, ok := m.GetTargetUnion().(*Compare_Value); ok {
		return x.Value
	}
	return nil
}

func (m *Compare) GetRangeEnd() []byte {
	if m != nil {
		return m.RangeEnd
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Compare) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Compare_Value)(nil),
	}
}

// From google paxosdb paper:
// Our implementation hinges around a powerful primitive which we call MultiOp. All other database
// operations except for iteration are implemented as a single call to MultiOp. A MultiOp is applied atomically
// and consists of three components:
// 1. A list of tests called guard. Each test in guard checks a single entry in the database. It may check
// for the absence or presence of a value, or compare with a given value. Two different tests in the guard
// may apply to the same or different entries in the database. All tests in the guard are applied and
// MultiOp returns the results. If all tests are true, MultiOp executes t op (see item 2 below), otherwise
// it executes f op (see item 3 below).
// 2. A list of database operations called t op. Each operation in the list is either an insert, delete, or
// lookup operation, and applies to a single database entry. Two different operations in the list may apply
// to the same or different entries in the database. These operations are executed
// if guard evaluates to
// true.
// 3. A list of database operations called f op. Like t op, but executed if guard evaluates to false.
type TxnRequest struct {
	// compare is a list of predicates representing a conjunction of terms.
	// If the comparisons succeed, then the success requests will be processed in order,
	// and the response will contain their respective responses in order.
	// If the comparisons fail, then the failure requests will be processed in order,
	// and the response will contain their respective responses in order.
	Compare []*Compare `protobuf:"bytes,1,rep,name=compare,proto3" json:"compare,omitempty"`
	// success is a list of requests which will be applied when compare evaluates to true.
	Success []*RequestOp `protobuf:"bytes,2,rep,name=success,proto3" json:"success,omitempty"`
	// failure is a list of requests which will be applied when compare evaluates to false.
	Failure              []*RequestOp `protobuf:"bytes,3,rep,name=failure,proto3" json:"failure,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TxnRequest) Reset()         { *m = TxnRequest{} }
func (m *TxnRequest) String() string { return proto.CompactTextString(m) }
func (*TxnRequest) ProtoMessage()    {}
func (*TxnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{12}
}

func (m *TxnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnRequest.Unmarshal(m, b)
}
func (m *TxnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnRequest.Marshal(b, m, deterministic)
}
func (m *TxnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnRequest.Merge(m, src)
}
func (m *TxnRequest) XXX_Size() int {
	return xxx_messageInfo_TxnRequest.Size(m)
}
func (m *TxnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxnRequest proto.InternalMessageInfo

func (m *TxnRequest) GetCompare() []*Compare {
	if m != nil {
		return m.Compare
	}
	return nil
}

func (m *TxnRequest) GetSuccess() []*RequestOp {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *TxnRequest) GetFailure() []*RequestOp {
	if m != nil {
		return m.Failure
	}
	return nil
}

type TxnResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// succeeded is set to true if the compare evaluated to true or false otherwise.
	Succeeded bool `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	// responses is a list of responses corresponding to the results from applying
	// success if succeeded is true or failure if succeeded is false.
	Responses            []*ResponseOp `protobuf:"bytes,3,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TxnResponse) Reset()         { *m = TxnResponse{} }
func (m *TxnResponse) String() string { return proto.CompactTextString(m) }
func (*TxnResponse) ProtoMessage()    {}
func (*TxnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{13}
}

func (m *TxnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnResponse.Unmarshal(m, b)
}
func (m *TxnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnResponse.Marshal(b, m, deterministic)
}
func (m *TxnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnResponse.Merge(m, src)
}
func (m *TxnResponse) XXX_Size() int {
	return xxx_messageInfo_TxnResponse.Size(m)
}
func (m *TxnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxnResponse proto.InternalMessageInfo

func (m *TxnResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TxnResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

func (m *TxnResponse) GetResponses() []*ResponseOp {
	if m != nil {
		return m.Responses
	}
	return nil
}

type SnapshotRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotRequest) Reset()         { *m = SnapshotRequest{} }
func (m *SnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*SnapshotRequest) ProtoMessage()    {}
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{14}
}

func (m *SnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotRequest.Unmarshal(m, b)
}
func (m *SnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotRequest.Marshal(b, m, deterministic)
}
func (m *SnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotRequest.Merge(m, src)
}
func (m *SnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_SnapshotRequest.Size(m)
}
func (m *SnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotRequest proto.InternalMessageInfo

type SnapshotResponse struct {
	// header has the current key-value store information. The first header in the snapshot
	// stream indicates the point in time of the snapshot.
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// remaining_bytes is the number of blob bytes to be sent after this message
	RemainingBytes uint64 `protobuf:"varint,2,opt,name=remaining_bytes,json=remainingBytes,proto3" json:"remaining_bytes,omitempty"`
	// blob contains the next chunk of the snapshot in the snapshot stream.
	Blob                 []byte   `protobuf:"bytes,3,opt,name=blob,proto3" json:"blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotResponse) Reset()         { *m = SnapshotResponse{} }
func (m *SnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*SnapshotResponse) ProtoMessage()    {}
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{15}
}

func (m *SnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotResponse.Unmarshal(m, b)
}
func (m *SnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotResponse.Marshal(b, m, deterministic)
}
func (m *SnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotResponse.Merge(m, src)
}
func (m *SnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_SnapshotResponse.Size(m)
}
func (m *SnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotResponse proto.InternalMessageInfo

func (m *SnapshotResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SnapshotResponse) GetRemainingBytes() uint64 {
	if m != nil {
		return m.RemainingBytes
	}
	return 0
}

func (m *SnapshotResponse) GetBlob() []byte {
	if m != nil {
		return m.Blob
	}
	return nil
}

type Member struct {
	// ID is the member ID for this member.
	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// name is the human-readable name of the member. If the member is not started, the name will be an empty string.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// peerURLs is the list of URLs the member exposes to the cluster for communication.
	PeerURLs []string `protobuf:"bytes,3,rep,name=peerURLs,proto3" json:"peerURLs,omitempty"`
	// clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
	ClientURLs []string `protobuf:"bytes,4,rep,name=clientURLs,proto3" json:"clientURLs,omitempty"`
	// isLearner indicates if the member is raft learner.
	IsLearner            bool     `protobuf:"varint,5,opt,name=isLearner,proto3" json:"isLearner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{16}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetPeerURLs() []string {
	if m != nil {
		return m.PeerURLs
	}
	return nil
}

func (m *Member) GetClientURLs() []string {
	if m != nil {
		return m.ClientURLs
	}
	return nil
}

func (m *Member) GetIsLearner() bool {
	if m != nil {
		return m.IsLearner
	}
	return false
}

type MemberAddRequest struct {
	// peerURLs is the list of URLs the added member will use to communicate with the cluster.
	PeerURLs []string `protobuf:"bytes,1,rep,name=peerURLs,proto3" json:"peerURLs,omitempty"`
	// isLearner indicates if the added member is raft learner.
	IsLearner            bool     `protobuf:"varint,2,opt,name=isLearner,proto3" json:"isLearner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberAddRequest) Reset()         { *m = MemberAddRequest{} }
func (m *MemberAddRequest) String() string { return proto.CompactTextString(m) }
func (*MemberAddRequest) ProtoMessage()    {}
func (*MemberAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{17}
}

func (m *MemberAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberAddRequest.Unmarshal(m, b)
}
func (m *MemberAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberAddRequest.Marshal(b, m, deterministic)
}
func (m *MemberAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberAddRequest.Merge(m, src)
}
func (m *MemberAddRequest) XXX_Size() int {
	return xxx_messageInfo_MemberAddRequest.Size(m)
}
func (m *MemberAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemberAddRequest proto.InternalMessageInfo

func (m *MemberAddRequest) GetPeerURLs() []string {
	if m != nil {
		return m.PeerURLs
	}
	return nil
}

func (m *MemberAddRequest) GetIsLearner() bool {
	if m != nil {
		return m.IsLearner
	}
	return false
}

type MemberAddResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// member is the member information for the added member.
	Member *Member `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	// members is a list of all members after adding the new member.
	Members              []*Member `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MemberAddResponse) Reset()         { *m = MemberAddResponse{} }
func (m *MemberAddResponse) String() string { return proto.CompactTextString(m) }
func (*MemberAddResponse) ProtoMessage()    {}
func (*MemberAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{18}
}

func (m *MemberAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberAddResponse.Unmarshal(m, b)
}
func (m *MemberAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberAddResponse.Marshal(b, m, deterministic)
}
func (m *MemberAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberAddResponse.Merge(m, src)
}
func (m *MemberAddResponse) XXX_Size() int {
	return xxx_messageInfo_MemberAddResponse.Size(m)
}
func (m *MemberAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MemberAddResponse proto.InternalMessageInfo

func (m *MemberAddResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MemberAddResponse) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (m *MemberAddResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type MemberRemoveRequest struct {
	// ID is the member ID of the member to remove.
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberRemoveRequest) Reset()         { *m = MemberRemoveRequest{} }
func (m *MemberRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*MemberRemoveRequest) ProtoMessage()    {}
func (*MemberRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{19}
}

func (m *MemberRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberRemoveRequest.Unmarshal(m, b)
}
func (m *MemberRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberRemoveRequest.Marshal(b, m, deterministic)
}
func (m *MemberRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberRemoveRequest.Merge(m, src)
}
func (m *MemberRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_MemberRemoveRequest.Size(m)
}
func (m *MemberRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemberRemoveRequest proto.InternalMessageInfo

func (m *MemberRemoveRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type MemberRemoveResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// members is a list of all members after removing the member.
	Members              []*Member `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MemberRemoveResponse) Reset()         { *m = MemberRemoveResponse{} }
func (m *MemberRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*MemberRemoveResponse) ProtoMessage()    {}
func (*MemberRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{20}
}

func (m *MemberRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberRemoveResponse.Unmarshal(m, b)
}
func (m *MemberRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberRemoveResponse.Marshal(b, m, deterministic)
}
func (m *MemberRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberRemoveResponse.Merge(m, src)
}
func (m *MemberRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_MemberRemoveResponse.Size(m)
}
func (m *MemberRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MemberRemoveResponse proto.InternalMessageInfo

func (m *MemberRemoveResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MemberRemoveResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type MemberRaftAttrUpdateRequest struct {
	// ID is the member ID of the member to update.
	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// peerURLs is the new list of URLs the member will use to communicate with the cluster.
	PeerURLs             []string `protobuf:"bytes,2,rep,name=peerURLs,proto3" json:"peerURLs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberRaftAttrUpdateRequest) Reset()         { *m = MemberRaftAttrUpdateRequest{} }
func (m *MemberRaftAttrUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*MemberRaftAttrUpdateRequest) ProtoMessage()    {}
func (*MemberRaftAttrUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{21}
}

func (m *MemberRaftAttrUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberRaftAttrUpdateRequest.Unmarshal(m, b)
}
func (m *MemberRaftAttrUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberRaftAttrUpdateRequest.Marshal(b, m, deterministic)
}
func (m *MemberRaftAttrUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberRaftAttrUpdateRequest.Merge(m, src)
}
func (m *MemberRaftAttrUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_MemberRaftAttrUpdateRequest.Size(m)
}
func (m *MemberRaftAttrUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberRaftAttrUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemberRaftAttrUpdateRequest proto.InternalMessageInfo

func (m *MemberRaftAttrUpdateRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MemberRaftAttrUpdateRequest) GetPeerURLs() []string {
	if m != nil {
		return m.PeerURLs
	}
	return nil
}

type MemberRaftAttrUpdateResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// members is a list of all members after updating the member.
	Members              []*Member `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MemberRaftAttrUpdateResponse) Reset()         { *m = MemberRaftAttrUpdateResponse{} }
func (m *MemberRaftAttrUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*MemberRaftAttrUpdateResponse) ProtoMessage()    {}
func (*MemberRaftAttrUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{22}
}

func (m *MemberRaftAttrUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberRaftAttrUpdateResponse.Unmarshal(m, b)
}
func (m *MemberRaftAttrUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberRaftAttrUpdateResponse.Marshal(b, m, deterministic)
}
func (m *MemberRaftAttrUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberRaftAttrUpdateResponse.Merge(m, src)
}
func (m *MemberRaftAttrUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_MemberRaftAttrUpdateResponse.Size(m)
}
func (m *MemberRaftAttrUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberRaftAttrUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MemberRaftAttrUpdateResponse proto.InternalMessageInfo

func (m *MemberRaftAttrUpdateResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MemberRaftAttrUpdateResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

// Attributes represents all the non-raft related attributes of an member.
type Attributes struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ClientUrls           []string `protobuf:"bytes,2,rep,name=client_urls,json=clientUrls,proto3" json:"client_urls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attributes) Reset()         { *m = Attributes{} }
func (m *Attributes) String() string { return proto.CompactTextString(m) }
func (*Attributes) ProtoMessage()    {}
func (*Attributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{23}
}

func (m *Attributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attributes.Unmarshal(m, b)
}
func (m *Attributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attributes.Marshal(b, m, deterministic)
}
func (m *Attributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attributes.Merge(m, src)
}
func (m *Attributes) XXX_Size() int {
	return xxx_messageInfo_Attributes.Size(m)
}
func (m *Attributes) XXX_DiscardUnknown() {
	xxx_messageInfo_Attributes.DiscardUnknown(m)
}

var xxx_messageInfo_Attributes proto.InternalMessageInfo

func (m *Attributes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attributes) GetClientUrls() []string {
	if m != nil {
		return m.ClientUrls
	}
	return nil
}

type MemberNoRaftAttrUpdateRequest struct {
	MemberId             uint64      `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	MemberAttributes     *Attributes `protobuf:"bytes,2,opt,name=member_attributes,json=memberAttributes,proto3" json:"member_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MemberNoRaftAttrUpdateRequest) Reset()         { *m = MemberNoRaftAttrUpdateRequest{} }
func (m *MemberNoRaftAttrUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*MemberNoRaftAttrUpdateRequest) ProtoMessage()    {}
func (*MemberNoRaftAttrUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{24}
}

func (m *MemberNoRaftAttrUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberNoRaftAttrUpdateRequest.Unmarshal(m, b)
}
func (m *MemberNoRaftAttrUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberNoRaftAttrUpdateRequest.Marshal(b, m, deterministic)
}
func (m *MemberNoRaftAttrUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberNoRaftAttrUpdateRequest.Merge(m, src)
}
func (m *MemberNoRaftAttrUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_MemberNoRaftAttrUpdateRequest.Size(m)
}
func (m *MemberNoRaftAttrUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberNoRaftAttrUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemberNoRaftAttrUpdateRequest proto.InternalMessageInfo

func (m *MemberNoRaftAttrUpdateRequest) GetMemberId() uint64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *MemberNoRaftAttrUpdateRequest) GetMemberAttributes() *Attributes {
	if m != nil {
		return m.MemberAttributes
	}
	return nil
}

type MemberNoRaftAttrUpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberNoRaftAttrUpdateResponse) Reset()         { *m = MemberNoRaftAttrUpdateResponse{} }
func (m *MemberNoRaftAttrUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*MemberNoRaftAttrUpdateResponse) ProtoMessage()    {}
func (*MemberNoRaftAttrUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{25}
}

func (m *MemberNoRaftAttrUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberNoRaftAttrUpdateResponse.Unmarshal(m, b)
}
func (m *MemberNoRaftAttrUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberNoRaftAttrUpdateResponse.Marshal(b, m, deterministic)
}
func (m *MemberNoRaftAttrUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberNoRaftAttrUpdateResponse.Merge(m, src)
}
func (m *MemberNoRaftAttrUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_MemberNoRaftAttrUpdateResponse.Size(m)
}
func (m *MemberNoRaftAttrUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberNoRaftAttrUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MemberNoRaftAttrUpdateResponse proto.InternalMessageInfo

type MemberPromoteRequest struct {
	// ID is the member ID of the member to promote.
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberPromoteRequest) Reset()         { *m = MemberPromoteRequest{} }
func (m *MemberPromoteRequest) String() string { return proto.CompactTextString(m) }
func (*MemberPromoteRequest) ProtoMessage()    {}
func (*MemberPromoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{26}
}

func (m *MemberPromoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberPromoteRequest.Unmarshal(m, b)
}
func (m *MemberPromoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberPromoteRequest.Marshal(b, m, deterministic)
}
func (m *MemberPromoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberPromoteRequest.Merge(m, src)
}
func (m *MemberPromoteRequest) XXX_Size() int {
	return xxx_messageInfo_MemberPromoteRequest.Size(m)
}
func (m *MemberPromoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberPromoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemberPromoteRequest proto.InternalMessageInfo

func (m *MemberPromoteRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type MemberPromoteResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// members is a list of all members after promoting the member.
	Members              []*Member `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MemberPromoteResponse) Reset()         { *m = MemberPromoteResponse{} }
func (m *MemberPromoteResponse) String() string { return proto.CompactTextString(m) }
func (*MemberPromoteResponse) ProtoMessage()    {}
func (*MemberPromoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{27}
}

func (m *MemberPromoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberPromoteResponse.Unmarshal(m, b)
}
func (m *MemberPromoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberPromoteResponse.Marshal(b, m, deterministic)
}
func (m *MemberPromoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberPromoteResponse.Merge(m, src)
}
func (m *MemberPromoteResponse) XXX_Size() int {
	return xxx_messageInfo_MemberPromoteResponse.Size(m)
}
func (m *MemberPromoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberPromoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MemberPromoteResponse proto.InternalMessageInfo

func (m *MemberPromoteResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MemberPromoteResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type MoveLeaderRequest struct {
	// targetID is the node ID for the new leader.
	TargetID             uint64   `protobuf:"varint,1,opt,name=targetID,proto3" json:"targetID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveLeaderRequest) Reset()         { *m = MoveLeaderRequest{} }
func (m *MoveLeaderRequest) String() string { return proto.CompactTextString(m) }
func (*MoveLeaderRequest) ProtoMessage()    {}
func (*MoveLeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{28}
}

func (m *MoveLeaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveLeaderRequest.Unmarshal(m, b)
}
func (m *MoveLeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveLeaderRequest.Marshal(b, m, deterministic)
}
func (m *MoveLeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveLeaderRequest.Merge(m, src)
}
func (m *MoveLeaderRequest) XXX_Size() int {
	return xxx_messageInfo_MoveLeaderRequest.Size(m)
}
func (m *MoveLeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveLeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveLeaderRequest proto.InternalMessageInfo

func (m *MoveLeaderRequest) GetTargetID() uint64 {
	if m != nil {
		return m.TargetID
	}
	return 0
}

type MoveLeaderResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MoveLeaderResponse) Reset()         { *m = MoveLeaderResponse{} }
func (m *MoveLeaderResponse) String() string { return proto.CompactTextString(m) }
func (*MoveLeaderResponse) ProtoMessage()    {}
func (*MoveLeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{29}
}

func (m *MoveLeaderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveLeaderResponse.Unmarshal(m, b)
}
func (m *MoveLeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveLeaderResponse.Marshal(b, m, deterministic)
}
func (m *MoveLeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveLeaderResponse.Merge(m, src)
}
func (m *MoveLeaderResponse) XXX_Size() int {
	return xxx_messageInfo_MoveLeaderResponse.Size(m)
}
func (m *MoveLeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveLeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveLeaderResponse proto.InternalMessageInfo

func (m *MoveLeaderResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type MemberListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberListRequest) Reset()         { *m = MemberListRequest{} }
func (m *MemberListRequest) String() string { return proto.CompactTextString(m) }
func (*MemberListRequest) ProtoMessage()    {}
func (*MemberListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{30}
}

func (m *MemberListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberListRequest.Unmarshal(m, b)
}
func (m *MemberListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberListRequest.Marshal(b, m, deterministic)
}
func (m *MemberListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberListRequest.Merge(m, src)
}
func (m *MemberListRequest) XXX_Size() int {
	return xxx_messageInfo_MemberListRequest.Size(m)
}
func (m *MemberListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemberListRequest proto.InternalMessageInfo

type MemberListResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// members is a list of all members associated with the cluster.
	Members              []*Member `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MemberListResponse) Reset()         { *m = MemberListResponse{} }
func (m *MemberListResponse) String() string { return proto.CompactTextString(m) }
func (*MemberListResponse) ProtoMessage()    {}
func (*MemberListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{31}
}

func (m *MemberListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberListResponse.Unmarshal(m, b)
}
func (m *MemberListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberListResponse.Marshal(b, m, deterministic)
}
func (m *MemberListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberListResponse.Merge(m, src)
}
func (m *MemberListResponse) XXX_Size() int {
	return xxx_messageInfo_MemberListResponse.Size(m)
}
func (m *MemberListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MemberListResponse proto.InternalMessageInfo

func (m *MemberListResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MemberListResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{32}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// leader is the member ID which the responding member believes is the current leader.
	Leader uint64 `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	// isLearner indicates if the member is raft learner.
	IsLearner bool `protobuf:"varint,3,opt,name=isLearner,proto3" json:"isLearner,omitempty"`
	// raftIndex is the current raft committed index of the responding member.
	RaftIndex uint64 `protobuf:"varint,4,opt,name=raftIndex,proto3" json:"raftIndex,omitempty"`
	// raftTerm is the current raft term of the responding member.
	RaftTerm uint64 `protobuf:"varint,5,opt,name=raftTerm,proto3" json:"raftTerm,omitempty"`
	// raftAppliedIndex is the current raft applied index of the responding member.
	RaftAppliedIndex uint64 `protobuf:"varint,6,opt,name=raftAppliedIndex,proto3" json:"raftAppliedIndex,omitempty"`
	// dbSize is the size of the backend database physically allocated, in bytes, of the responding member.
	DbSize int64 `protobuf:"varint,7,opt,name=dbSize,proto3" json:"dbSize,omitempty"`
	// dbSizeInUse is the size of the backend database logically in use, in bytes, of the responding member.
	DbSizeInUse          int64    `protobuf:"varint,8,opt,name=dbSizeInUse,proto3" json:"dbSizeInUse,omitempty"`
	Errors               []string `protobuf:"bytes,9,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{33}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *StatusResponse) GetLeader() uint64 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *StatusResponse) GetIsLearner() bool {
	if m != nil {
		return m.IsLearner
	}
	return false
}

func (m *StatusResponse) GetRaftIndex() uint64 {
	if m != nil {
		return m.RaftIndex
	}
	return 0
}

func (m *StatusResponse) GetRaftTerm() uint64 {
	if m != nil {
		return m.RaftTerm
	}
	return 0
}

func (m *StatusResponse) GetRaftAppliedIndex() uint64 {
	if m != nil {
		return m.RaftAppliedIndex
	}
	return 0
}

func (m *StatusResponse) GetDbSize() int64 {
	if m != nil {
		return m.DbSize
	}
	return 0
}

func (m *StatusResponse) GetDbSizeInUse() int64 {
	if m != nil {
		return m.DbSizeInUse
	}
	return 0
}

func (m *StatusResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type DefragmentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefragmentRequest) Reset()         { *m = DefragmentRequest{} }
func (m *DefragmentRequest) String() string { return proto.CompactTextString(m) }
func (*DefragmentRequest) ProtoMessage()    {}
func (*DefragmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{34}
}

func (m *DefragmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefragmentRequest.Unmarshal(m, b)
}
func (m *DefragmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefragmentRequest.Marshal(b, m, deterministic)
}
func (m *DefragmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefragmentRequest.Merge(m, src)
}
func (m *DefragmentRequest) XXX_Size() int {
	return xxx_messageInfo_DefragmentRequest.Size(m)
}
func (m *DefragmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DefragmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DefragmentRequest proto.InternalMessageInfo

type DefragmentResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DefragmentResponse) Reset()         { *m = DefragmentResponse{} }
func (m *DefragmentResponse) String() string { return proto.CompactTextString(m) }
func (*DefragmentResponse) ProtoMessage()    {}
func (*DefragmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6091a60c3d6a4306, []int{35}
}

func (m *DefragmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefragmentResponse.Unmarshal(m, b)
}
func (m *DefragmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefragmentResponse.Marshal(b, m, deterministic)
}
func (m *DefragmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefragmentResponse.Merge(m, src)
}
func (m *DefragmentResponse) XXX_Size() int {
	return xxx_messageInfo_DefragmentResponse.Size(m)
}
func (m *DefragmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DefragmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DefragmentResponse proto.InternalMessageInfo

func (m *DefragmentResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterEnum("serverpb.RangeRequest_SortOrder", RangeRequest_SortOrder_name, RangeRequest_SortOrder_value)
	proto.RegisterEnum("serverpb.RangeRequest_SortTarget", RangeRequest_SortTarget_name, RangeRequest_SortTarget_value)
	proto.RegisterEnum("serverpb.Compare_CompareResult", Compare_CompareResult_name, Compare_CompareResult_value)
	proto.RegisterEnum("serverpb.Compare_CompareTarget", Compare_CompareTarget_name, Compare_CompareTarget_value)
	proto.RegisterType((*KeyValue)(nil), "serverpb.KeyValue")
	proto.RegisterType((*Metadata)(nil), "serverpb.Metadata")
	proto.RegisterType((*ResponseHeader)(nil), "serverpb.ResponseHeader")
	proto.RegisterType((*RangeRequest)(nil), "serverpb.RangeRequest")
	proto.RegisterType((*RangeResponse)(nil), "serverpb.RangeResponse")
	proto.RegisterType((*PutRequest)(nil), "serverpb.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "serverpb.PutResponse")
	proto.RegisterType((*DeleteRangeRequest)(nil), "serverpb.DeleteRangeRequest")
	proto.RegisterType((*DeleteRangeResponse)(nil), "serverpb.DeleteRangeResponse")
	proto.RegisterType((*RequestOp)(nil), "serverpb.RequestOp")
	proto.RegisterType((*ResponseOp)(nil), "serverpb.ResponseOp")
	proto.RegisterType((*Compare)(nil), "serverpb.Compare")
	proto.RegisterType((*TxnRequest)(nil), "serverpb.TxnRequest")
	proto.RegisterType((*TxnResponse)(nil), "serverpb.TxnResponse")
	proto.RegisterType((*SnapshotRequest)(nil), "serverpb.SnapshotRequest")
	proto.RegisterType((*SnapshotResponse)(nil), "serverpb.SnapshotResponse")
	proto.RegisterType((*Member)(nil), "serverpb.Member")
	proto.RegisterType((*MemberAddRequest)(nil), "serverpb.MemberAddRequest")
	proto.RegisterType((*MemberAddResponse)(nil), "serverpb.MemberAddResponse")
	proto.RegisterType((*MemberRemoveRequest)(nil), "serverpb.MemberRemoveRequest")
	proto.RegisterType((*MemberRemoveResponse)(nil), "serverpb.MemberRemoveResponse")
	proto.RegisterType((*MemberRaftAttrUpdateRequest)(nil), "serverpb.MemberRaftAttrUpdateRequest")
	proto.RegisterType((*MemberRaftAttrUpdateResponse)(nil), "serverpb.MemberRaftAttrUpdateResponse")
	proto.RegisterType((*Attributes)(nil), "serverpb.Attributes")
	proto.RegisterType((*MemberNoRaftAttrUpdateRequest)(nil), "serverpb.MemberNoRaftAttrUpdateRequest")
	proto.RegisterType((*MemberNoRaftAttrUpdateResponse)(nil), "serverpb.MemberNoRaftAttrUpdateResponse")
	proto.RegisterType((*MemberPromoteRequest)(nil), "serverpb.MemberPromoteRequest")
	proto.RegisterType((*MemberPromoteResponse)(nil), "serverpb.MemberPromoteResponse")
	proto.RegisterType((*MoveLeaderRequest)(nil), "serverpb.MoveLeaderRequest")
	proto.RegisterType((*MoveLeaderResponse)(nil), "serverpb.MoveLeaderResponse")
	proto.RegisterType((*MemberListRequest)(nil), "serverpb.MemberListRequest")
	proto.RegisterType((*MemberListResponse)(nil), "serverpb.MemberListResponse")
	proto.RegisterType((*StatusRequest)(nil), "serverpb.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "serverpb.StatusResponse")
	proto.RegisterType((*DefragmentRequest)(nil), "serverpb.DefragmentRequest")
	proto.RegisterType((*DefragmentResponse)(nil), "serverpb.DefragmentResponse")
}

func init() { proto.RegisterFile("server_pb.proto", fileDescriptor_6091a60c3d6a4306) }

var fileDescriptor_6091a60c3d6a4306 = []byte{
	// 1442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x5d, 0x6f, 0xe3, 0xc4,
	0x1a, 0x8e, 0xed, 0x36, 0x89, 0xdf, 0xa4, 0x69, 0x3a, 0xfd, 0x38, 0xd1, 0xd9, 0xee, 0x6e, 0x8e,
	0xcf, 0x39, 0x50, 0x2d, 0xa2, 0xa0, 0x80, 0x84, 0x84, 0x84, 0x76, 0xd3, 0x36, 0x4b, 0xa3, 0xcd,
	0xb6, 0x65, 0xd2, 0xae, 0x60, 0x6f, 0x22, 0xa7, 0x9e, 0x76, 0xad, 0x75, 0x6c, 0x33, 0x1e, 0x57,
	0xed, 0x0a, 0x09, 0x71, 0xc3, 0x05, 0x77, 0x5c, 0x21, 0xc4, 0x0f, 0xe0, 0x96, 0xff, 0xc2, 0x1f,
	0x42, 0xf3, 0x65, 0x3b, 0x49, 0xcb, 0x4a, 0x41, 0xda, 0xab, 0xcc, 0xfb, 0x39, 0xcf, 0x3c, 0xf3,
	0xce, 0xeb, 0x99, 0xc0, 0x6a, 0x42, 0xe8, 0x15, 0xa1, 0xa3, 0x78, 0xbc, 0x1b, 0xd3, 0x88, 0x45,
	0xa8, 0x2a, 0x15, 0xf1, 0xd8, 0xe9, 0x40, 0xf5, 0x19, 0xb9, 0x79, 0xe1, 0x06, 0x29, 0x41, 0x4d,
	0xb0, 0x5e, 0x93, 0x9b, 0x96, 0xd1, 0x36, 0x76, 0xea, 0x98, 0x0f, 0xd1, 0x06, 0x2c, 0x5f, 0x71,
	0x53, 0x6b, 0x59, 0xe8, 0xa4, 0xe0, 0x3c, 0x81, 0xea, 0x73, 0xc2, 0x5c, 0xcf, 0x65, 0x2e, 0xda,
	0x82, 0xf2, 0x51, 0xe4, 0x91, 0xfe, 0x81, 0x08, 0x5b, 0xc2, 0x4a, 0x42, 0xdb, 0x60, 0xef, 0x07,
	0x69, 0xc2, 0x08, 0xed, 0x1f, 0xb4, 0x4c, 0x61, 0xca, 0x15, 0x8e, 0x0f, 0x0d, 0x4c, 0x92, 0x38,
	0x0a, 0x13, 0x72, 0x48, 0x5c, 0x8f, 0x50, 0x74, 0x1f, 0xe0, 0x5c, 0x9a, 0x47, 0xbe, 0xa7, 0x72,
	0xd9, 0x4a, 0xd3, 0xf7, 0xd0, 0x3d, 0xb0, 0x27, 0x64, 0x32, 0x96, 0x56, 0x99, 0xae, 0x2a, 0x15,
	0xd2, 0x48, 0xdd, 0x0b, 0x36, 0x62, 0x84, 0x4e, 0x5a, 0x96, 0x34, 0x72, 0xc5, 0x29, 0xa1, 0x13,
	0xe7, 0x27, 0x0b, 0xea, 0xd8, 0x0d, 0x2f, 0x09, 0x26, 0xdf, 0xa6, 0x24, 0x61, 0xb7, 0xac, 0x52,
	0xc4, 0x87, 0x97, 0x64, 0x44, 0x42, 0x99, 0xbc, 0xce, 0xe3, 0xc3, 0x4b, 0xd2, 0x0b, 0x3d, 0x4e,
	0x41, 0xe0, 0x4f, 0x7c, 0x26, 0x12, 0x5b, 0x58, 0x0a, 0xe8, 0x31, 0x40, 0x12, 0x51, 0x36, 0x8a,
	0xa8, 0x47, 0x68, 0x6b, 0xa9, 0x6d, 0xec, 0x34, 0x3a, 0xed, 0x5d, 0xcd, 0xea, 0x6e, 0x71, 0xc2,
	0xdd, 0x61, 0x44, 0xd9, 0x31, 0xf7, 0xc3, 0x76, 0xa2, 0x87, 0x68, 0x0f, 0x6a, 0x22, 0x01, 0x73,
	0xe9, 0x25, 0x61, 0x82, 0xdf, 0x46, 0xe7, 0x3f, 0x7f, 0x93, 0xe1, 0x54, 0x38, 0x62, 0x31, 0xad,
	0x1c, 0x23, 0x07, 0xea, 0x09, 0xa1, 0xbe, 0x1b, 0xf8, 0x6f, 0xdc, 0x71, 0x40, 0x5a, 0xe5, 0xb6,
	0xb1, 0x53, 0xc5, 0x53, 0x3a, 0xbe, 0xb6, 0xd7, 0xe4, 0x26, 0x19, 0x45, 0x61, 0x70, 0xd3, 0xaa,
	0x08, 0x87, 0x2a, 0x57, 0x1c, 0x87, 0xc1, 0x8d, 0x20, 0x3d, 0x4a, 0x43, 0x26, 0xad, 0x55, 0x61,
	0xb5, 0x85, 0x86, 0x9b, 0x9d, 0x5d, 0xb0, 0x33, 0xec, 0xa8, 0x0a, 0x4b, 0x47, 0xc7, 0x47, 0xbd,
	0x66, 0x09, 0x01, 0x94, 0xbb, 0xc3, 0xfd, 0xde, 0xd1, 0x41, 0xd3, 0x40, 0x35, 0xa8, 0x1c, 0xf4,
	0xa4, 0x60, 0x3a, 0x6d, 0x80, 0x1c, 0x29, 0xaa, 0x80, 0xf5, 0xac, 0xf7, 0x4d, 0xb3, 0x84, 0x6c,
	0x58, 0x7e, 0xd1, 0x1d, 0x9c, 0xf5, 0x9a, 0x86, 0xf3, 0xb3, 0x01, 0x2b, 0x6a, 0x65, 0x72, 0xf7,
	0xd1, 0xc7, 0x50, 0x7e, 0x25, 0x2a, 0x40, 0x6c, 0x48, 0xad, 0xd3, 0x2a, 0x50, 0x30, 0x55, 0x21,
	0x58, 0xf9, 0xa1, 0xff, 0x81, 0xf5, 0xfa, 0x2a, 0x69, 0x99, 0x6d, 0x6b, 0xa7, 0xd6, 0x41, 0xb9,
	0xbb, 0x2e, 0x63, 0xcc, 0xcd, 0x08, 0xc1, 0xd2, 0x24, 0xa2, 0x44, 0xec, 0x5a, 0x15, 0x8b, 0x31,
	0xdf, 0x4a, 0xb1, 0x38, 0xb1, 0x5f, 0x16, 0x96, 0x82, 0xf3, 0x29, 0xc0, 0x49, 0xca, 0xee, 0xae,
	0x8e, 0xec, 0x0c, 0x98, 0xc5, 0x33, 0xf0, 0x18, 0x6a, 0x22, 0x6a, 0xd1, 0x65, 0x38, 0xfb, 0x80,
	0x0e, 0x48, 0x40, 0x18, 0xf9, 0x07, 0xc5, 0xe9, 0xb8, 0xb0, 0x3e, 0x95, 0x64, 0x61, 0x52, 0x5b,
	0x50, 0xf1, 0x44, 0x22, 0x39, 0x87, 0x85, 0xb5, 0xe8, 0xfc, 0x6a, 0x82, 0xad, 0xd0, 0x1d, 0xc7,
	0xe8, 0x0b, 0x58, 0xa1, 0x52, 0x18, 0x09, 0x10, 0x6a, 0x82, 0xad, 0xdb, 0x0b, 0xf7, 0xb0, 0x84,
	0xeb, 0xca, 0x5d, 0xa8, 0xd1, 0x67, 0x50, 0xd3, 0xe1, 0x71, 0xca, 0xc4, 0x54, 0xb5, 0xce, 0x46,
	0x1e, 0x9c, 0x6f, 0xc4, 0x61, 0x09, 0x83, 0x72, 0x3d, 0x49, 0x19, 0x3a, 0x81, 0x0d, 0x1d, 0x28,
	0x81, 0xa9, 0xe9, 0x2d, 0x91, 0x61, 0x3b, 0xcf, 0x30, 0xcf, 0xe9, 0x61, 0x09, 0x23, 0x15, 0x5b,
	0x30, 0x16, 0xa1, 0xb0, 0xeb, 0x50, 0x94, 0xc4, 0x14, 0x94, 0xd3, 0xeb, 0x70, 0x1e, 0xca, 0xe9,
	0x75, 0xb8, 0x67, 0x43, 0x45, 0x49, 0xce, 0xef, 0x26, 0x80, 0x26, 0xf4, 0x38, 0x46, 0x4f, 0xa0,
	0x41, 0x95, 0x34, 0xc5, 0xce, 0xbf, 0xe6, 0xd8, 0x51, 0x7b, 0x50, 0xc2, 0x2b, 0x3a, 0x40, 0x82,
	0xfa, 0x1c, 0xea, 0x59, 0x86, 0x9c, 0xa0, 0xcd, 0x19, 0x82, 0xb2, 0xe8, 0x9a, 0x76, 0xe6, 0x14,
	0x0d, 0x61, 0x33, 0x8b, 0xbd, 0x85, 0xa3, 0xfb, 0x77, 0x70, 0x94, 0x25, 0x5b, 0xd7, 0xd1, 0x45,
	0x96, 0x8a, 0x80, 0x72, 0x9a, 0x36, 0x67, 0x68, 0x9a, 0x07, 0xc4, 0x89, 0x02, 0xa8, 0x6a, 0xd1,
	0xf9, 0xd3, 0x84, 0xca, 0x7e, 0x34, 0x89, 0x5d, 0xca, 0x99, 0x2f, 0x53, 0x92, 0xa4, 0x01, 0x13,
	0xf4, 0x34, 0x3a, 0x0f, 0xf3, 0x6c, 0xca, 0x45, 0xff, 0x62, 0xe1, 0x86, 0x95, 0x3b, 0x0f, 0x54,
	0xed, 0xd2, 0x7c, 0x4b, 0xa0, 0x6a, 0x96, 0xca, 0x5d, 0x9f, 0x2a, 0x2b, 0x3f, 0x55, 0x5b, 0xfa,
	0x50, 0xf3, 0x05, 0xd5, 0x0f, 0x4b, 0xea, 0x58, 0x4f, 0x9f, 0x36, 0x6f, 0xe6, 0xb4, 0xbd, 0x84,
	0x95, 0x29, 0x60, 0xbc, 0xb3, 0xf5, 0xbe, 0x3a, 0xeb, 0x0e, 0x9a, 0x25, 0xde, 0x08, 0xbf, 0xc4,
	0xbd, 0xee, 0x69, 0x0f, 0x37, 0x0d, 0xde, 0x2b, 0x07, 0xbd, 0xe1, 0xb0, 0x69, 0xa2, 0x15, 0xb0,
	0x8f, 0x8e, 0x4f, 0x47, 0xd2, 0xcb, 0x12, 0x01, 0x5f, 0xf7, 0x87, 0xa7, 0xcd, 0xa5, 0xcc, 0x22,
	0xc4, 0x65, 0xe7, 0xbf, 0x59, 0x6e, 0xd5, 0x3e, 0xb3, 0xae, 0x59, 0xd2, 0x9d, 0xd4, 0xd8, 0x6b,
	0x40, 0x5d, 0xae, 0x68, 0x94, 0x86, 0x7e, 0x14, 0x3a, 0xbf, 0x18, 0x00, 0x79, 0x9d, 0xa2, 0x0f,
	0xa0, 0x72, 0x2e, 0x73, 0xb4, 0x0c, 0xd1, 0x1d, 0xd7, 0xe6, 0x08, 0xc2, 0xda, 0x03, 0x7d, 0x08,
	0x95, 0x24, 0x3d, 0x3f, 0x27, 0x89, 0x6e, 0xa5, 0xeb, 0xc5, 0x26, 0xa1, 0xce, 0x3b, 0xd6, 0x3e,
	0xdc, 0xfd, 0xc2, 0xf5, 0x83, 0x54, 0xb4, 0xd4, 0xbb, 0xdd, 0x95, 0x0f, 0x6f, 0xf4, 0xb5, 0x42,
	0x69, 0x2c, 0xd0, 0x91, 0xb6, 0xc1, 0x16, 0x73, 0x13, 0x4f, 0xf5, 0xa4, 0x2a, 0xce, 0x15, 0xa8,
	0x03, 0xb6, 0xae, 0xad, 0x44, 0x01, 0xda, 0x98, 0x4f, 0x79, 0x1c, 0xe3, 0xdc, 0xcd, 0x59, 0x83,
	0xd5, 0x61, 0xe8, 0xc6, 0xc9, 0xab, 0x48, 0x37, 0x19, 0xe7, 0x07, 0x03, 0x9a, 0xb9, 0x6e, 0x61,
	0xac, 0xef, 0xc3, 0x2a, 0x25, 0x13, 0xd7, 0x0f, 0xfd, 0xf0, 0x72, 0x34, 0xbe, 0x61, 0x24, 0x51,
	0x77, 0x94, 0x46, 0xa6, 0xde, 0xe3, 0x5a, 0xfe, 0x55, 0x1a, 0x07, 0xd1, 0x58, 0x55, 0xa2, 0x18,
	0x3b, 0x3f, 0x1a, 0x50, 0x7e, 0x2e, 0xae, 0x32, 0xa8, 0x01, 0x66, 0x76, 0x91, 0x32, 0xfb, 0x07,
	0xdc, 0x3d, 0x74, 0x27, 0xf2, 0xcb, 0x63, 0x63, 0x31, 0x46, 0xff, 0x86, 0x6a, 0x4c, 0x08, 0x3d,
	0xc3, 0x03, 0xb9, 0x70, 0x1b, 0x67, 0x32, 0x7a, 0xc0, 0x2f, 0x51, 0x3e, 0x09, 0x99, 0xb0, 0x2e,
	0x09, 0x6b, 0x41, 0xc3, 0x39, 0xf5, 0x93, 0x01, 0x71, 0x69, 0x48, 0xa8, 0xb8, 0x72, 0x54, 0x71,
	0xae, 0x70, 0x06, 0xd0, 0x94, 0x38, 0xba, 0x9e, 0xa7, 0x4b, 0xaa, 0x38, 0x9b, 0x31, 0x33, 0xdb,
	0x54, 0x36, 0x73, 0x36, 0xdb, 0x6f, 0x06, 0xac, 0x15, 0xd2, 0x2d, 0xcc, 0xed, 0x0e, 0x94, 0xe5,
	0x45, 0x4f, 0x35, 0xc3, 0x66, 0x1e, 0x21, 0xd3, 0x63, 0x65, 0x47, 0x8f, 0xa0, 0x22, 0x47, 0xba,
	0x22, 0xe6, 0x5d, 0xb5, 0x83, 0xf3, 0x7f, 0x58, 0x57, 0x2a, 0x32, 0x89, 0xae, 0xb2, 0xcf, 0xef,
	0xcc, 0x06, 0x38, 0x0c, 0x36, 0xa6, 0xdd, 0x16, 0x5e, 0x46, 0x01, 0x9c, 0xf9, 0x36, 0x70, 0x7d,
	0xb8, 0xa7, 0x54, 0xee, 0x05, 0xeb, 0x32, 0x46, 0xcf, 0x62, 0xcf, 0x65, 0x77, 0x81, 0x9c, 0xda,
	0x23, 0x73, 0x7a, 0x8f, 0x9c, 0xef, 0x60, 0xfb, 0xf6, 0x54, 0xef, 0x64, 0x21, 0x5d, 0x00, 0x3e,
	0xa7, 0x3f, 0x4e, 0x55, 0xf1, 0x8b, 0x6a, 0x36, 0x0a, 0xd5, 0xfc, 0x10, 0x6a, 0xb2, 0x3e, 0x47,
	0x29, 0x0d, 0x34, 0x7c, 0x5d, 0xb2, 0x34, 0x48, 0x9c, 0xef, 0xe1, 0xbe, 0xcc, 0x7a, 0x14, 0xdd,
	0xce, 0xc6, 0xd4, 0xcb, 0xc0, 0x98, 0x79, 0x19, 0x74, 0x61, 0x4d, 0x19, 0xdd, 0x0c, 0xc7, 0xfc,
	0xad, 0x23, 0xc7, 0x88, 0x9b, 0xd2, 0x3d, 0xd7, 0x38, 0x6d, 0x78, 0x70, 0x17, 0x00, 0xf5, 0x6d,
	0x7b, 0x4f, 0x17, 0xc9, 0x09, 0x8d, 0x26, 0xd1, 0x9d, 0xfb, 0xe4, 0xa4, 0xb0, 0x39, 0xe3, 0xf7,
	0x4e, 0x36, 0xe1, 0x23, 0x58, 0x7b, 0x1e, 0x5d, 0x91, 0x81, 0xcc, 0x90, 0x9f, 0x6b, 0xf9, 0x25,
	0xc9, 0x10, 0x66, 0xb2, 0xf3, 0x14, 0x50, 0x31, 0x60, 0xe1, 0x1b, 0xee, 0xba, 0x6e, 0x00, 0x03,
	0x3f, 0xc9, 0x3a, 0x2e, 0x05, 0x54, 0x54, 0xbe, 0x13, 0x06, 0x56, 0x61, 0x65, 0xc8, 0x5c, 0x96,
	0x26, 0x1a, 0xc4, 0x1f, 0x26, 0x34, 0xb4, 0x66, 0x61, 0x04, 0x5b, 0x50, 0x0e, 0x64, 0x84, 0xec,
	0xf5, 0x4a, 0x9a, 0x6e, 0x8b, 0xd6, 0x4c, 0x5b, 0xe4, 0x56, 0xfe, 0x34, 0xed, 0x87, 0x1e, 0xb9,
	0x16, 0x97, 0x8f, 0x25, 0x9c, 0x2b, 0xf8, 0xb6, 0xe8, 0x87, 0xab, 0xe8, 0xcf, 0x85, 0x87, 0x2c,
	0x7a, 0x04, 0x4d, 0x3e, 0xee, 0xc6, 0x71, 0xe0, 0x13, 0x4f, 0x26, 0x28, 0x0b, 0x9f, 0x39, 0x3d,
	0xc7, 0xe6, 0x8d, 0x87, 0xfe, 0x1b, 0x22, 0x9e, 0x7c, 0x16, 0x56, 0x12, 0x6a, 0x43, 0x4d, 0x8e,
	0xfa, 0xe1, 0x59, 0x42, 0xc4, 0x8b, 0xcf, 0xc2, 0x45, 0x15, 0x8f, 0x24, 0x94, 0x46, 0x34, 0x69,
	0xd9, 0xe2, 0x2c, 0x2a, 0x89, 0x6f, 0xe6, 0x01, 0xb9, 0xa0, 0xee, 0xe5, 0x84, 0x84, 0xd9, 0x66,
	0x3e, 0xe5, 0x6f, 0x98, 0x5c, 0xb9, 0x28, 0x95, 0x7b, 0xf0, 0x32, 0xfb, 0x43, 0x62, 0x5c, 0x16,
	0xff, 0x50, 0x7c, 0xf2, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x06, 0x14, 0x70, 0x61, 0xb4, 0x10,
	0x00, 0x00,
}
